#!/bin/bash
#
# chkconfig: 2345 15 15
# description: gkrellmd monitor for remote viewing of system info using
#              gkrellm as a client
# processname: gkrellmd
# pidfile: /var/run/gkrellmd.pid
# config: /etc/gkrellmd.conf

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0

case "$1" in
  start)
	gprintf "Starting gkrellmd: "
        daemon gkrellmd -d
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/gkrellmd
	;;
  stop)
	gprintf "Shutting down gkrellmd: "
	killproc gkrellmd
	RETVAL=$?

	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/gkrellmd
	;;
  restart|reload)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  status)
	status gkrellmd
	RETVAL=$?
	;;
  *)
	gprintf "Usage: gkrellmd {start|stop|status|restart|reload}\n"
	exit 1
esac

exit $RETVAL

